CREATE TABLE BRAND(
	id INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(250) NOT NULL
);

CREATE TABLE CATEGORY(
	id INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(250) NOT NULL
);

CREATE TABLE SELLER(
	id INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(250) NOT NULL
);

CREATE TABLE PRODUCT(
	id INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(250) NOT NULL,
	PRICE INT NOT NULL,
	SIZE VARCHAR(10) NOT NULL,
	QUANTITY INT NOT NULL,
	SKUCODE VARCHAR(250) NOT NULL,
	BRAND_ID INT  NULL,
	foreign key (BRAND_ID) references BRAND(ID),
	CAT_ID INT  NULL,
	foreign key (CAT_ID) references CATEGORY(ID),
	SELLER_ID INT  NULL,
	foreign key(SELLER_ID) references SELLER(ID)
);